### PR TITLE
Merging Two Versions of StructFieldsForQuery

### PR DESCRIPTION
**Pull request by petersng**
The two `StructFieldsForQuery` differ a bit more than I thought between crawler and processor.  This is an attempt to merge them together.  

@innainu can you take a look at the function and see if it smells right?  I think it looks good.

### CODE REVIEW

**Comment by innainu** [comment]
There are 2 versions bc we use the prefix in the processor but the crawler persistence isn't updated yet to use the prefix. If this is the one copied from the processor then it's right!

**Comment by petersng** [comment]
Originally I copied over the version from the crawler.  Then I added updates from the processor version to combine it.  Does it seem correct?

**Comment by innainu** [comment]
Hm.. it looks copied over correctly, but I noticed you deleted utils_test.go in the processor repo and the tests in this repo don't look as complete? https://github.com/joincivil/civil-events-processor/blob/master/pkg/persistence/postgres/utils_test.go

**Comment by petersng** [comment]
I mentioned this in slack, but `utils_test.go` in the processor repo was broken up and each test was moved to it's appropriate location.  For instance `TestStringToCommonAddressesList` was moved to https://github.com/joincivil/go-common/blob/master/pkg/strings/strings_test.go#L109.

**Pull request merged**
